### Crear producto
POST http://localhost:8080/productos
Content-Type: application/json

{
  "nombre": "Auriculares Gamer",
  "precio": 60000,
  "stock": 8,
  "categoria": "Audio"
}
### CONSULTAR PRODUCTOS
GET http://localhost:8080/productos


### ORDENAR POR PRECIO
GET http://localhost:8080/productos/ordenar/precio


### ORDENAR POR NOMBRE
GET http://localhost:8080/productos/ordenar/nombre


### CREAR PRODUCTO
POST http://localhost:8080/productos
Content-Type: application/json

{
  "nombre": "Auriculares Gamer",
  "precio": 60000,
  "stock": 8,
  "categoria": "Audio"
}


